# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the test-application-default-profile.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    healtcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.commute-service-discovery.credentials.uri}/eureka/


spring:
  jpa:
    database: postgresql
    show-sql: false

commute:
  security:
   auth:
    jwt:
      secret: |
        Uhosp9k5nBhHnYM1HZS2/982vLQGwniP/bsG/biZGROQUk+yZNM4AErANMn7kx7591IVq9kfFvtjDbGzb2v8Fg==


